// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetJokeOKCode is the HTTP code returned for type GetJokeOK
const GetJokeOKCode int = 200

/*GetJokeOK A new joke with a new name

swagger:response getJokeOK
*/
type GetJokeOK struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewGetJokeOK creates GetJokeOK with default headers values
func NewGetJokeOK() *GetJokeOK {

	return &GetJokeOK{}
}

// WithPayload adds the payload to the get joke o k response
func (o *GetJokeOK) WithPayload(payload string) *GetJokeOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get joke o k response
func (o *GetJokeOK) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetJokeOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}
