// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetJokeHandlerFunc turns a function with the right signature into a get joke handler
type GetJokeHandlerFunc func(GetJokeParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetJokeHandlerFunc) Handle(params GetJokeParams) middleware.Responder {
	return fn(params)
}

// GetJokeHandler interface for that can handle valid get joke params
type GetJokeHandler interface {
	Handle(GetJokeParams) middleware.Responder
}

// NewGetJoke creates a new http.Handler for the get joke operation
func NewGetJoke(ctx *middleware.Context, handler GetJokeHandler) *GetJoke {
	return &GetJoke{Context: ctx, Handler: handler}
}

/*GetJoke swagger:route GET /joke getJoke

Get a newly made joke

Get a newly made joke

*/
type GetJoke struct {
	Context *middleware.Context
	Handler GetJokeHandler
}

func (o *GetJoke) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetJokeParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
