// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
)

// NewPostGetJobsParams creates a new PostGetJobsParams object
// no default values defined in spec.
func NewPostGetJobsParams() PostGetJobsParams {

	return PostGetJobsParams{}
}

// PostGetJobsParams contains all the bound params for the post get jobs operation
// typically these are obtained from a http.Request
//
// swagger:parameters PostGetJobs
type PostGetJobsParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*List of URLs to obtain info from
	  Required: true
	  In: body
	*/
	ListOfUrls []string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewPostGetJobsParams() beforehand.
func (o *PostGetJobsParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body []string
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("listOfUrls", "body"))
			} else {
				res = append(res, errors.NewParseError("listOfUrls", "body", "", err))
			}
		} else {
			// no validation required on inline body
			o.ListOfUrls = body
		}
	} else {
		res = append(res, errors.Required("listOfUrls", "body"))
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
