// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "webscraper/models"
)

// PostGetJobsOKCode is the HTTP code returned for type PostGetJobsOK
const PostGetJobsOKCode int = 200

/*PostGetJobsOK OK

swagger:response postGetJobsOK
*/
type PostGetJobsOK struct {

	/*
	  In: Body
	*/
	Payload models.Success `json:"body,omitempty"`
}

// NewPostGetJobsOK creates PostGetJobsOK with default headers values
func NewPostGetJobsOK() *PostGetJobsOK {

	return &PostGetJobsOK{}
}

// WithPayload adds the payload to the post get jobs o k response
func (o *PostGetJobsOK) WithPayload(payload models.Success) *PostGetJobsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post get jobs o k response
func (o *PostGetJobsOK) SetPayload(payload models.Success) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostGetJobsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make(models.Success, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}
