// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi SimpleWebScrape
Simple web scraper project


    Schemes:
      http
    Host: localhost
    BasePath: /
    Version: 0.0.1

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
