// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Apple Take Home Project
Take home project for Apple job


    Schemes:
      http
    Host: localhost
    BasePath: /
    Version: 0.0.1

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
