// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Take home project for Apple job",
    "title": "Apple Take Home Project",
    "version": "0.0.1"
  },
  "paths": {
    "/joke": {
      "get": {
        "description": "Get a newly made joke",
        "summary": "Get a newly made joke",
        "responses": {
          "200": {
            "description": "A new joke with a new name",
            "schema": {
              "type": "string"
            }
          }
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Take home project for Apple job",
    "title": "Apple Take Home Project",
    "version": "0.0.1"
  },
  "paths": {
    "/joke": {
      "get": {
        "description": "Get a newly made joke",
        "summary": "Get a newly made joke",
        "responses": {
          "200": {
            "description": "A new joke with a new name",
            "schema": {
              "type": "string"
            }
          }
        }
      }
    }
  }
}`))
}
